### ISSUE TITLE
Let's Encrypt certificate renewal failing

### ISSUE THREAD

**Issue by stu177** [webmin/webmin#1124]
Currently, all Lets Encrypt renewals through webmin are failing and throwing the following error:

````
An error occurred requesting a new certificate for example.com, www.example.com from Let's Encrypt : Web-based validation failed : <pre>Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/example.com.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel):
** Invalid input **
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): An unexpected error occurred:
EOFError
Please see the logfiles in /var/log/letsencrypt for more details.
</pre>
````
The same error is displayed when running a renewal through the web interface and recieved in email after a scheduled renewal.

The following is from the letsencrypt.log for this renewal:

````
2019-10-03 10:14:22,235:DEBUG:certbot.main:certbot version: 0.31.0
2019-10-03 10:14:22,237:DEBUG:certbot.main:Arguments: ['-a', 'webroot', '-d', 'alpha.host.webbedfeet.uk', '--webroot-path', '/var/$
2019-10-03 10:14:22,238:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,Plugi$
2019-10-03 10:14:22,273:DEBUG:certbot.log:Root logging level set at 20
2019-10-03 10:14:22,274:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-10-03 10:14:22,275:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2019-10-03 10:14:22,276:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f6534a9d208>
Prep: True
2019-10-03 10:14:22,277:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x$
2019-10-03 10:14:22,277:INFO:certbot.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2019-10-03 10:14:22,286:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), a$
2019-10-03 10:14:22,288:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2019-10-03 10:14:22,291:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
2019-10-03 10:14:22,805:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 20$
2019-10-03 10:14:22,806:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 03 Oct 2019 09:14:22 GMT
Content-Type: application/json
Content-Length: 724
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert",
  "wZaB2iEezRM": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2019-10-03 10:14:22,824:INFO:certbot.renewal:Cert not yet due for renewal
2019-10-03 10:14:22,825:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1243, in certonly
    should_get_cert, lineage = _find_cert(config, domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 286, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 323, in _find_lineage_for_domains_and_certname
    return _handle_identical_cert_request(config, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 217, in _handle_identical_cert_request
    default=0, force_interactive=True)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 155, in menu
    code, selection = self._get_valid_int_ans(len(choices))
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 418, in _get_valid_int_ans
    ans = input_with_timeout(input_msg)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 85, in input_with_timeout
    raise EOFError
EOFError
2019-10-03 10:14:22,828:ERROR:certbot.log:An unexpected error occurred:
````

**Comment by kibeb** [comment]
I had the same problem, from September. One certificate after the other failed to renew, "Cert not yet due for renewal". At the same time all of these certs where already renewed and saved under /etc/letsencrypt/live/, some of them having multiple directories there and just one of them was renewed, but none of them was copied to /home/*/ssl.* so it would work in webmin (Apache). 
What solved (or "solved") it was PR #1101. 
But I wonder if #1101 is the best way to do it, as (IMHO) if certbot is forced to renew the same cert multiple times, if multiple directories exist as I had them, and if there is a limit for forced renew like 5 a week (https://letsencrypt.org/docs/rate-limits/), it could end badly... again -- IMHO.

**Comment by stu177** [comment]
Ah, I didn't see #1101, yeh to me that is completely wrong to force renewal. That should definitely not be the default behaviour as like you said there are limits.

In the Certbot user guide, it says this should only be used for manual renewals and not with automated tools or daily schedules.

The default behaviour should just be to keep the existing cert if it's not yet due for renewal.

**Comment by stu177** [comment]
Another thing I've noticed is that the certificates in the home directory for each user are not being updated with the newly generated certs. This could be because the tool isn't finishing the renewal and updating these files:

````
ssl.cert
ssl.combined
ssl.everything
ssl.key
````

**Comment by chris001** [comment]
@stu177 
Exactly. I wrote a bash script to symlink all the `ssl.*` names, in the users' home directories, to the real cert file in `/etc/letsencrypt/live/`.  Note: The various cert filenames are different, so you have to be careful and match them correctly, or else it breaks `ssl` for the users' services.  When you get it right, it works great.

**Comment by stu177** [comment]
I'm also getting issues with certificates now trying to renew every hour even though the certificate is not due for renewal creating dozens of emails a day saying that there has been an issue with renewing the SSL certificate.

I don't know what's been changed recently with Lets Encrypt and accounts, but something has defiantly been changed.
