### ISSUE TITLE
Let's encrypt fails for mail.domain.com

### ISSUE THREAD

**Issue by Zen4All** [webmin/webmin#529]
Lately when requesting a ssl certificate through let's encrypt I get the error below. I noticed it is also requesting the certificate for the mail sub-domain, which is good, but it does not seem to work on my system.
(actual domain name has been replaced)
```
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying domain.nl...
domain.nl verified!
Verifying www.domain.nl...
www.domain.nl verified!
Verifying mail.domain.nl...
Wrote file to /home/domain/public_html/.well-known/acme-challenge/BjK5PoG6O_ueHyNnsMHGpA9-qsgUK61PvHHpztuYGCA, but couldn't download http://mail.domain.nl/.well-known/acme-challenge/BjK5PoG6O_ueHyNnsMHGpA9-qsgUK61PvHHpztuYGCA
Traceback (most recent call last):
  File "/usr/share/webmin/webmin/acme_tiny.py", line 203, in <module>
    main(sys.argv[1:])
  File "/usr/share/webmin/webmin/acme_tiny.py", line 199, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/usr/share/webmin/webmin/acme_tiny.py", line 154, in get_crt
    domain, challenge_status))
ValueError: mail.domain.nl challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'http://mail.domain.nl/.well-known/acme-challenge/BjK5PoG6O_ueHyNnsMHGpA9-qsgUK61PvHHpztuYGCA', u'hostname': u'mail.domain.nl', u'addressUsed': u'37.46.136.159', u'port': u'80', u'addressesResolved': [u'37.46.136.159']}], u'keyAuthorization': u'BjK5PoG6O_ueHyNnsMHGpA9-qsgUK61PvHHpztuYGCA.-rSLzWCsKda_o-N4rRPeOYGqUCsq5MUJ1Dtwl4Q2QpI', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/Y1Vo9CtH5opF_X3XpwQr-juDusef70WmRzpVGsAry0k/984709538', u'token': u'BjK5PoG6O_ueHyNnsMHGpA9-qsgUK61PvHHpztuYGCA', u'error': {u'status': 403, u'type': u'urn:acme:error:unauthorized', u'detail': u'Invalid response from http://mail.domain.nl/.well-known/acme-challenge/BjK5PoG6O_ueHyNnsMHGpA9-qsgUK61PvHHpztuYGCA: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p"'}, u'type': u'http-01'}
```
System information:
```
Operating system	Ubuntu Linux 16.04.1
Webmin version	1.831 
Virtualmin version	5.07
Theme version	Authentic Theme 18.40
```

**Comment by qooob** [comment]
Hi,

You must make sure, that you have appropriate records in DNS and HTTPd servers. In other words, they should be world accessible from your browser.

If you want to have certificate for `mailman.example.com` you must make sure that going to this address in your browser really works.

**Comment by Zen4All** [comment]
When I go to mail.mydomain.nl, I am presented with the 'Apache2 Ubuntu Default Page' page. So it is accessible.

**Comment by qooob** [comment]
Does it have redirections enabled?

If you create in your domain root ( like `public_html`) a folder with a file, will you be able yo access it?

**Comment by Zen4All** [comment]
The domain has an up and running website, which resides in the public_html folder. The mail sub-domain seems to point to the default var/www/html folder, which has the standard index.html in it.

To answer your question: When I create a new folder in public_html, like 'test' and put a file i it, like 'index.html', I can see the resulting page in a browser. An empty folder will result in a 403.

**Comment by qooob** [comment]
That appears to be incorrect.

The subdomain that you want to issue certificate for needs to be aliased under the same parent domain and executed under the same user.

In case it falls to default, that might not work due to permissions.

**Comment by Zen4All** [comment]
I do not use the DNS buit in virtualmin, but an external service where my domains are registered.
The suggested DNS records were used to create the necessary dns records
```
domain.nl.	IN	A	XX.XX.136.159
www.domain.nl.	IN	A	XX.XX.136.159
ftp.domain.nl.	IN	A	XX.XX.136.159
m.domain.nl.	IN	A	XX.XX.136.159
localhost.domain.nl.	IN	A	127.0.0.1
admin.domain.nl.	IN	A	XX.XX.136.159
mail.domain.nl.	IN	A	XX.XX.136.159
domain.nl.	IN	MX	5 mail.domain.nl.
domain.nl.	IN	TXT	"v=spf1 a mx domain.nl ip4:XX.XX.136.159 ?all"
```
Within virtualmin I only created the main domain as "domain.nl". Should I add the mail sub-domain?

**Comment by qooob** [comment]
There are many ways of doing it. You just need to make sure that Virtualmin can write to the directory of the virtual server as it's run as the server user, as far as I'm aware. 

All domains that you want to have certificates for needs to be validated first using regular http request. Make sure that it happens. Your `mail.domain.nl` should have access to the document root of the `domain.nl`.
